project:
  type: website
  output-dir: docs

website:
  title: "Jona's blog"
  site-url: https://jaj42.github.io/blog/
  description: "Things I want to share"
  navbar:
    right:
      - icon: github
        href: https://github.com/jaj42
      - icon: gitlab
        href: https://framagit.org/users/jaj/projects
      - icon: mastodon
        href: https://mastodon.social/@jaj
      - icon: rss
        href: index.xml
format:
  html:
    theme:
      light: flatly
      dark: slate
    css: styles.css